#乙設定ファイル
#設定方法
# : 以降を変更してください
#test: aaa -> test: abc

#牢屋の座標
#ゲーム内でも変更可能です。
# x座標,y座標,z座標,ワールド名
jail: "0,0,0,world"

#未実装　現在は使えません
#以下あらしへのメッセージの変更　[乙]は自動
#変数　%p% プレーヤー名　%px% %py% %pz% プレーヤーの座標
# %x% %y% %z% 牢屋の座標
otu.m.otu.now: "( ﾟω^ )ゝ 荒らし乙であります！"
#otu.m.otu.
otu.m.runa.now: "動くと罪が重くなりますよ!"